# Generated by Django 3.1.7 on 2021-03-26 08:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210325_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='/placeholder.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
