# Generated by Django 3.1.7 on 2021-03-26 08:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210326_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder_y55v6h.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
